# Generated by Django 4.0.3 on 2022-06-24 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_work_day_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='work_time',
            field=models.CharField(choices=[('F', 'Full-Time'), ('H', 'Half-Time'), ('Q', '3/4 Time')], max_length=1),
        ),
        migrations.AlterField(
            model_name='free_days',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.profile'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.profile'),
        ),
        migrations.AlterField(
            model_name='work_day',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.profile'),
        ),
    ]
